extension["新服杂碎"]={
	intro:"关于但不限于新服的各种玩意儿<br>更新日期：2019.06.05",
	author:"苏婆玛丽奥",
	netdisk:"",
	forum:"",
	version:"2.9",
	files:["xf_yiji.jpg","extension.js","liuyao.jpg","majun.jpg","lvqian.jpg","zhangji.jpg",
		"zhanggong.jpg","panjun.jpg","liuyan.jpg","weiwenzhugezhi.jpg","yanjun.jpg","wangcan.jpg",
		"zhoufang.jpg","wolong_card.jpg","baosanniang.jpg","fengchu_card.jpg","re_yuji.jpg",
		"zhaotongzhaoguang.jpg","sp_taishici.jpg","xuanjian_card.jpg",
		"pangdegong.jpg","re_jsp_pangtong.jpg","re_zhangliang.jpg","lvdai.jpg","caoying.jpg",
		"duji.jpg","zhangqiying.jpg","fanchou.jpg","lvkai.jpg","guosi.jpg","lijue.jpg","xurong.jpg",
		"simahui.jpg","shuijing_card.jpg","simazhao.jpg","wangyuanji.jpg","xf_huangquan.jpg",
		"xf_tangzi.jpg","xf_sufei.jpg","sp_xiahoushi.jpg"],
	size:"6.76MB"
};
extension["新国战"]={
	intro:"◇2019版新国战规则与武将改动扩展",
	author:"苏婆玛丽奥",
	netdisk:"",
	forum:"",
	version:"3.4",
	files:["extension.js","chaoming.mp3","default.mp3"],
	size:"5MB"
};
