extension["新服杂碎"]={
	intro:"关于但不限于新服的各种玩意儿<br>更新日期：2019.05.30",
	author:"苏婆玛丽奥",
	netdisk:"",
	forum:"",
	version:"2.7",
	files:["xuanjian_card.jpg","extension.js","majun.jpg","lvqian.jpg","zhangji.jpg","zhanggong.jpg",
		"panjun.jpg","liuyan.jpg","weiwenzhugezhi.jpg","yanjun.jpg","wangcan.jpg","zhoufang.jpg",
		"wolong_card.jpg","baosanniang.jpg","fengchu_card.jpg","re_yuji.jpg","zhaotongzhaoguang.jpg",
		"sp_taishici.jpg","liuyao.jpg","xf_yiji.jpg","pangdegong.jpg","re_jsp_pangtong.jpg",
		"re_zhangliang.jpg","lvdai.jpg","caoying.jpg","duji.jpg","zhangqiying.jpg","fanchou.jpg",
		"lvkai.jpg","guosi.jpg","lijue.jpg","xurong.jpg","simahui.jpg","shuijing_card.jpg",
		"simazhao.jpg","wangyuanji.jpg"],
	size:"6.26MB"
};
